version: '3.9'
services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  # el_shopperino_frontend:
  #   build:
  #     context: .
  #     dockerfile: ./backend/el_shopperino_project/docker/frontend/Dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./docker/nginx/el_shopperino.conf:/etc/nginx/conf.d/default.conf
  el_shopperino_backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/el_shopperino-Dockerfile
    # command: gunicorn el_shopperino_project.el_shopperino_core.wsgi --bind 0.0.0.0:8000 --workers=4 --threads 4
    ports:
      - 8000:8000
    depends_on:
      - el_shopperinodb

  el_shopperinodb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=el_shopperinodb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
