# Generated by Django 4.0.1 on 2022-06-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profilemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={},
        ),
    ]
